const BASE_API_URL = "http://localhost:4600";

const USERS_API_ENDPOINT = `${BASE_API_URL}/api/users`;
const TECHNOLOGIES_API_ENDPOINT = `${BASE_API_URL}/api/technologies`;
const PROJECTS_API_ENDPOINT = `${BASE_API_URL}/api/projects`;
const MESSAGES_API_ENDPOINT = `${BASE_API_URL}/api/messages`;

export {
  USERS_API_ENDPOINT,
  TECHNOLOGIES_API_ENDPOINT,
  PROJECTS_API_ENDPOINT,
  BASE_API_URL,
  MESSAGES_API_ENDPOINT,
};
